apiVersion: v1
kind: Pod
metadata:
  namespace: lab
  name: bastion
spec:
  containers:
    - name: centos
      image: centos:latest
      command:
      - sh
      - -c
      - while true; do sleep 60; done
